const perform = (z, bundle) => {
  const options = {
    url:
      'https://gregoryspest.pestroutes.com/api/customer/' + bundle.inputData.id,
    method: 'GET',
    headers: {},
    params: {
      authenticationToken: bundle.authData.authenticationToken,
      authenticationKey: bundle.authData.authenticationKey,
    },
  };

  return z.request(options).then((response) => {
    response.throwForStatus();
    const results = response.json;

    // You can do any parsing you need for results here before returning them

    return results.customer;
  });
};

module.exports = {
  operation: {
    perform: perform,
    inputFields: [
      {
        key: 'id',
        label: 'ID',
        type: 'string',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
    ],
    sample: {
      customerID: '10666',
      billToAccountID: '10666',
      officeID: '1',
      fname: 'Paul',
      lname: 'Test Customer',
      companyName: '',
      spouse: null,
      commercialAccount: '0',
      status: '0',
      statusText: 'Inactive',
      email: 'Paulgregory7210@gmail.com',
      phone1: '9544019286',
      phone2: '',
      address: '5092 Palm Brooke Circle',
      city: 'West Palm Beach',
      state: 'FL',
      zip: '33417',
      billingCompanyName: '',
      billingFName: 'Paul',
      billingLName: 'Test Customer',
      billingCountryID: 'US',
      billingAddress: '5092 Palm Brooke Circle',
      billingCity: 'West Palm Beach',
      billingState: 'FL',
      billingZip: '33417',
      billingPhone: '9544019286',
      billingEmail: 'Paulgregory7210@gmail.com',
      lat: '26.747541',
      lng: '-80.110672',
      squareFeet: '0',
      addedByID: '10001',
      dateAdded: '2020-11-19 09:02:36',
      dateCancelled: '0000-00-00 00:00:00',
      dateUpdated: '2020-11-19 09:02:38',
      sourceID: null,
      source: null,
      aPay: 'No',
      preferredTechID: '0',
      paidInFull: '0',
      subscriptionIDs: null,
      balance: '0.00',
      balanceAge: '0',
      responsibleBalance: '0.00',
      responsibleBalanceAge: '0',
      customerLink: '',
      masterAccount: '0',
      preferredBillingDate: '0',
      paymentHoldDate: null,
      mostRecentCreditCardLastFour: null,
      mostRecentCreditCardExpirationDate: null,
      regionID: '0',
      mapCode: '',
      mapPage: '',
      specialScheduling: '',
      taxRate: '0.000000',
      smsReminders: '1',
      phoneReminders: '0',
      emailReminders: '1',
      customerSource: 'Employee Referral',
      customerSourceID: '14',
      appointmentIDs: null,
      ticketIDs: null,
      paymentIDs: null,
      unitIDs: [],
    },
    outputFields: [
      { key: 'customerID' },
      { key: 'billToAccountID' },
      { key: 'officeID' },
      { key: 'fname' },
      { key: 'lname' },
      { key: 'companyName' },
      { key: 'spouse' },
      { key: 'commercialAccount' },
      { key: 'status' },
      { key: 'statusText' },
      { key: 'email' },
      { key: 'phone1' },
      { key: 'phone2' },
      { key: 'address' },
      { key: 'city' },
      { key: 'state' },
      { key: 'zip' },
      { key: 'billingCompanyName' },
      { key: 'billingFName' },
      { key: 'billingLName' },
      { key: 'billingCountryID' },
      { key: 'billingAddress' },
      { key: 'billingCity' },
      { key: 'billingState' },
      { key: 'billingZip' },
      { key: 'billingPhone' },
      { key: 'billingEmail' },
      { key: 'lat' },
      { key: 'lng' },
      { key: 'squareFeet' },
      { key: 'addedByID' },
      { key: 'dateAdded' },
      { key: 'dateCancelled' },
      { key: 'dateUpdated' },
      { key: 'sourceID' },
      { key: 'source' },
      { key: 'aPay' },
      { key: 'preferredTechID' },
      { key: 'paidInFull' },
      { key: 'subscriptionIDs' },
      { key: 'balance' },
      { key: 'balanceAge' },
      { key: 'responsibleBalance' },
      { key: 'responsibleBalanceAge' },
      { key: 'customerLink' },
      { key: 'masterAccount' },
      { key: 'preferredBillingDate' },
      { key: 'paymentHoldDate' },
      { key: 'mostRecentCreditCardLastFour' },
      { key: 'mostRecentCreditCardExpirationDate' },
      { key: 'regionID' },
      { key: 'mapCode' },
      { key: 'mapPage' },
      { key: 'specialScheduling' },
      { key: 'taxRate' },
      { key: 'smsReminders' },
      { key: 'phoneReminders' },
      { key: 'emailReminders' },
      { key: 'customerSource' },
      { key: 'customerSourceID' },
      { key: 'appointmentIDs' },
      { key: 'ticketIDs' },
      { key: 'paymentIDs' },
    ],
  },
  key: 'get_customer_details',
  noun: 'customer',
  display: {
    label: 'Get Customer ',
    description: 'To get customer details by id',
    hidden: false,
    important: true,
  },
};
